"""Typed domain models for student academics and preferences."""

from app.models.academic import (
    AcademicRecord,
    CalculatedGPA,
    Course,
    CourseLevel,
    CourseStatus,
    GPARecord,
    GPAScope,
    GPAType,
    Grade,
    PreparationSignal,
    RecordSource,
    StandardizedTest,
    Term,
    TestScore,
)
from app.models.applicant import ApplicantStage, HighSchoolContext
from app.models.assessment import (
    ProfileAssessment,
    ProfileWarning,
    WarningSeverity,
    assess_profile,
)
from app.models.classification import (
    AcademicStanding,
    AdmissionCategory,
    AdmissionsBenchmark,
    ClassificationConfidence,
    ClassificationResult,
    ClassificationRule,
    GPABenchmark,
)
from app.models.college import (
    DatasetVersion,
    Institution,
    InstitutionFilters,
    MajorAdmissionType,
    Ownership,
    ProgramOffering,
    RefreshReport,
    ResidencySelectivity,
    TestPolicy,
)
from app.models.export import ExportedFile, ExportFormat, ExportResult
from app.models.holistic import Activity, HolisticProfile, HolisticReviewStatus
from app.models.preferences import (
    BudgetType,
    EntryTerm,
    RecommendationSettings,
    StudentPreferences,
    TestSubmissionPlan,
    ThresholdMode,
)
from app.models.ranking import (
    CategoryThresholdResult,
    ConsolidatedFitResult,
    FitComponent,
    FitConfidence,
    MajorFitResult,
)
from app.models.report import (
    CollegeReport,
    ComparisonRow,
    GapStatus,
    HolisticContext,
    ReportCandidate,
    SchoolReport,
    SourceReference,
)
from app.models.student import StudentProfile

__all__ = [
    "AcademicRecord",
    "AcademicStanding",
    "Activity",
    "AdmissionCategory",
    "AdmissionsBenchmark",
    "ApplicantStage",
    "BudgetType",
    "CalculatedGPA",
    "CategoryThresholdResult",
    "ClassificationConfidence",
    "ClassificationResult",
    "ClassificationRule",
    "CollegeReport",
    "ComparisonRow",
    "ConsolidatedFitResult",
    "Course",
    "CourseLevel",
    "CourseStatus",
    "DatasetVersion",
    "EntryTerm",
    "ExportFormat",
    "ExportResult",
    "ExportedFile",
    "FitComponent",
    "FitConfidence",
    "GPABenchmark",
    "GPARecord",
    "GPAScope",
    "GPAType",
    "GapStatus",
    "Grade",
    "HighSchoolContext",
    "HolisticContext",
    "HolisticProfile",
    "HolisticReviewStatus",
    "Institution",
    "InstitutionFilters",
    "MajorAdmissionType",
    "MajorFitResult",
    "Ownership",
    "PreparationSignal",
    "ProfileAssessment",
    "ProfileWarning",
    "ProgramOffering",
    "RecommendationSettings",
    "RecordSource",
    "RefreshReport",
    "ReportCandidate",
    "ResidencySelectivity",
    "SchoolReport",
    "SourceReference",
    "StandardizedTest",
    "StudentPreferences",
    "StudentProfile",
    "Term",
    "TestPolicy",
    "TestScore",
    "TestSubmissionPlan",
    "ThresholdMode",
    "WarningSeverity",
    "assess_profile",
]
